[package]
name = "davoxide"
description = "A WebDAV server written in Rust"
authors = ["Alexander Krantz <alex@krantz.dev>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.13"
dav-server = { version = "0.3.4", default-features = false, features = ["localfs"] }
tokio = { version = "1.20.0", features = ["macros", "rt", "rt-multi-thread"] }
