//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use async_graphql::Enum;
use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, Copy, Eq, Ord, PartialEq, PartialOrd, EnumIter, DeriveActiveEnum, Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action")]
pub enum Action {
    #[sea_orm(string_value = "deny")]
    Deny,
    #[sea_orm(string_value = "read")]
    Read,
    #[sea_orm(string_value = "modify")]
    Modify,
    #[sea_orm(string_value = "admin")]
    Admin,
}
