name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  binary:
    name: Binary
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.node-version
          cache: yarn
          cache-dependency-file: frontend/yarn.lock
      - uses: dtolnay/rust-toolchain@stable

      - run: yarn install --ignore-scripts
        working-directory: frontend
      - run: yarn build
        working-directory: frontend

      - run: cargo build --release

      - uses: actions/upload-artifact@v3
        with:
          name: davoxide
          path: target/release/davoxide

  docker:
    name: Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          flavor: |
            latest=auto
          images: ghcr.io/${{ github.repository_owner }}/davoxide
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

