name: Lint

on:
  - push

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.node-version
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - run: yarn install --ignore-scripts
        working-directory: frontend

      - run: yarn lint
        working-directory: frontend

  backend:
    name: Backend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.job }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ github.job }}-${{ runner.os }}-cargo-

      - run: cargo fmt --all --check

      # This is a workaround to prevent embedding from failing
      - run: mkdir -p frontend/dist && touch frontend/dist/tempfile
      - run: cargo clippy -- -D warnings
